global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'kianyarii1383@gmail.com'
    from: 'kianyarii1383@gmail.com'
    smarthost: 'smtp.example.com:587'
    auth_username: 'kianyarii1383@gmail.com'
    auth_password: ${EMAIL_PAT}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']