package localization

var English = map[string]interface{}{
	"firstName":           "first name",
	"lastName":            "last name",
	"phone":               "phone",
	"password":            "password",
	"confirmPassword":     "confirm password",
	"isAcceptTerms":       "terms and conditions",
	"nationalID":          "national ID",
	"registrationNumber":  "registration number",
	"iban":                "iban",
	"user":                "user",
	"address":             "address",
	"name":                "name",
	"province":            "province",
	"city":                "city",
	"page":                "page",
	"room":                "chat room",
	"notificationType":    "notification type",
	"notificationTypes":   "notification type",
	"notification":        "notification",
	"notificationSetting": "notification Setting",
	"email":               "email",
	"role":                "role",
	"permission":          "permission",
	"report":              "report",
	"paymentTerm":         "payment term",
	"news":                "news",
	"title":              "title",
	"media":               "media",
	"post":                "post",
	"like":                "like",
	"unlike":              "unlike",
	"errors": map[string]interface{}{
		"generic":                "an error occurred, please try again.",
		"numeric":                "The {0} should be a numeric value.",
		"fileRequired":           "File is required.",
		"minimumLength":          "The {0} Len must bigger than 7 characters.",
		"containsLowercase":      "The {0} should contain lowercase.",
		"containsUppercase":      "The {0} should contain uppercase.",
		"containsNumber":         "The {0} should contain number.",
		"containsSpecialChar":    "The {0} should contain special character.",
		"alreadyRegistered":      "Has been already registered with this {0}",
		"required":               "Field {0} required to fill",
		"e164":                   "Phone number u have entered is not correct",
		"eqfield":                "Password and {0} are not the same.",
		"eq":                     "Field {0} should be true.",
		"Expired":                "OTP is expired.",
		"email":                  "Email format is wrong.",
		"invalid":                "OTP is invalid.",
		"notRegistered":          "You have to register first.",
		"invalidAuthCredentials": "Username and password not matched",
		"expiredAuthToken":       "Your token has been expired. Please log in again.",
		"invalidAuthToken":       "There is a problem with your token.",
		"unauthorized":           "Please login first.",
		"awaitingApproval":       "Your account is awaiting admin approval.",
		"rejected":               "Your account has been rejected by admin.",
		"notExist":               "This {0} does not exist.",
		"alreadyExist":           "This {0} already exists.",
		"notFound":               "This {0} not found.",
		"notVerified":            "You have to verify your account first.",
		"notActive":              "This {0} is not active",
		"rateLimitExceed":        "Rate limit exceeded. try again later.",
		"installRateLimit":       "Active installation requests has been exceeded the limit.",
		"forbiddenError":         "Forbidden: Access to {0} is not allowed",
		"forbiddenStatus":        "Cannot do this action with this status.",
		"pending":                "Your request is pending.",
		"alreadyBlocked":         "This {0} has been already blocked.",
		"alreadyActive":          "This {0} has been already active.",
		"alreadyResolved":        "This {0} has been already resolved.",
		"alreadyArchived":        "This {0} has been already archived.",
		"statusNotChange":        "This {0} has been already have this status.",
		"alreadyCanceled":        "This {0} has been already canceled.",
		"alreadyRejected":        "This {0} has been already rejected.",
		"alreadyAccepted":        "This {0} has been already accepted.",
		"alreadyDraft":           "This {0} has been already drafted.",
	},
	"successMessage": map[string]interface{}{
		"userRegister":               "Registration Successful! Please check your messages to verify your account and complete the registration process.",
		"phoneVerification":          "Your phone has been successfully verified.",
		"login":                      "Logged in successfully.",
		"changeLogo":                 "Corporation logo has been changed.",
		"addAddress":                 "Address added successfully.",
		"editAddress":                "Address edited successfully.",
		"deleteAddress":              "Address deleted successfully.",
		"changePassword":             "Password changed successfully.",
		"forgotPassword":             "Please check your messages to verify your phone number.",
		"resetPassword":              "Password reset successfully.",
		"createAddress":              "Address created successfully.",
		"refreshToken":               "Your session has been successfully refreshed.",
		"readNotification":           "notification marked as read",
		"updateNotificationSetting":  "notification updated successfully",
		"completeRegister":           "Your registration has been completed successfully.",
		"emailVerification":          "Your email has been successfully verified.",
		"updateProfile":              "Profile has been updated successfully",
		"blockChatRoom":              "Chat room has been successfully blocked.",
		"unblockChatRoom":            "Chat room has been successfully unblocked.",
		"createRole":                 "New role has been created successfully.",
		"deleteRole":                 "New role has been deleted successfully.",
		"updateRole":                 "New role has been updated successfully.",
		"updateUserRoles":            "User roles has been updated successfully.",
		"createReport":               "Report has been successfully created.",
		"reportResolved":             "Report has been successfully resolved.",
		"banUser":                    "User get banned successfully.",
		"unBanUser":                  "User get unbanned successfully.",
		"createDraftNews":            "Draft news has been created successfully.",
		"editNews":                   "News has been updated successfully.",
		"publishNews":                "News has been successfully published.",
		"unpublishNews":              "News has been successfully drafted.",
		"deleteNews":                 "ُSelected news has been successfully deleted.",
		"addMedia":                   "Media has been added successfully.",
		"deleteMedia":                "Media has been deleted successfully.",
		"createPost":                 "Post has been created successfully.",
		"deletePost":                 "Post has been deleted successfully.",
		"editPost":                   "Post has been updated successfully.",
		"publishPost":                "Post has been successfully published.",
		"unpublishPost":              "Post has been successfully drafted.",
		"likePost":                   "Post has been liked successfully.",
		"unlikePost":                 "Post has been unliked successfully.",
	},
	"emailSubject": map[string]interface{}{
		"emailConfirmation": "Verify Your Email Address",
	},
}
