package localization

var Persian = map[string]interface{}{
	"firstName":           "نام",
	"lastName":            "نام خانوادگی",
	"phone":               "شماره تماس",
	"password":            "رمز عبور",
	"confirmPassword":     "تایید رمز عیور",
	"isAcceptTerms":       "تایید شرایط و مقررات",
	"nationalID":          "شناسه ملی",
	"registrationNumber":  "شماره ثبت",
	"iban":                "شماره شبا",
	"user":                "کاربر",
	"address":             "آدرس",
	"name":                "نام",
	"province":            "استان",
	"city":                "شهر",
	"page":                "صفحه",
	"room":                "اتاق گفتگو",
	"notificationType":    "نوع اعلان",
	"notificationTypes":   "نوع اعلانات",
	"notification":        "اعلان",
	"NotificationSetting": "تنظیمات اعلان",
	"email":               "ایمیل",
	"role":                "نقش",
	"permission":          "دسترسی",
	"paymentTerm":         "روش پرداخت",
	"news":                "اخبار",
	"title":              "عنوان",
	"media":               "محتوا",
	"post":                "پست",
	"like":                "لایک",
	"unlike":              "حذف لایک",
	"errors": map[string]interface{}{
		"generic":                "خطایی رخ داده است، لطفا دوباره تلاش کنید.",
		"numeric":                "`{0}` باید عدد باشد.",
		"fileRequired":           "وارد کردن فایل اجباری است.",
		"minimumLength":          "باید از 7 کاراکتر بیشتر باشد.",
		"containsLowercase":      "باید حتما دارای حرف کوچک باشد.",
		"containsUppercase":      "باید حتما دارای حرف بزرگ باشد.",
		"containsNumber":         "باید حتما دارای عدد باشد.",
		"containsSpecialChar":    "باید حتما دارای حروف خاص باشد.",
		"alreadyRegistered":      "قبلا با این {0} ثبت نام کرده است.",
		"required":               "بخش {0} باید کامل شود.",
		"e164":                   "شماره تلفن به درستی ثبت نشده است.",
		"eqfield":                "رمز عبور و {0} مطابقت ندارند.",
		"eq":                     "مقدار {0 باید درست باشد}",
		"Expired":                "رمز یکبار مصرف شما منقضی شده است.",
		"invalid":                "رمز یکبار مصرف وارد شده اشتباه است.",
		"notRegistered":          "ابتدا باید در سایت ثبت نام کنید.",
		"invalidAuthCredentials": "نام کاربری و رمز عبور تطابق ندارند.",
		"expiredAuthToken":       "نشست شما منقضی شده است. لطفا دوباره وارد شوید.",
		"invalidAuthToken":       "در توکن ورود شما اشکالی وجود دارد.",
		"unauthorized":           "ابتدا باید وارد شوید.",
		"awaitingApproval":       "حساب شما در انتظار تایید ادمین است.",
		"rejected":               "حساب شما توسط ادمین رد شده است.",
		"notExist":               "این {0} وجود ندارد.",
		"alreadyExist":           "این {0} قبلا وجود داشته است.",
		"notFound":               "این {0} پیدا نشد.",
		"notVerified":            "باید ابتدا حساب خود را فعال کنید.",
		"notActive":              "این {0} فعال نیست.",
		"rateLimitExceed":        "بیشتر از حد مجاز درخواست ثبت کرده اید.",
		"installRateLimit":       "تعداد درخواست های فعال شما از حدنساب عبور کرده است.",
		"forbiddenError":         "اجازه دسترسی به این {0} وجود ندارد.",
		"forbiddenStatus":        "اجازه انجام این کار را در این وضعیت ندارید.",
		"pending":                "این {0} حال بررسی است.",
		"email":                  "فرمت ایمیل نادرست است.",
		"alreadyBlocked":         "این {0} از پیش مسدود شده است.",
		"alreadyActive":          "این {0} از پیش فعال شده است.",
		"alreadyResolved":        "این {0} قبلا بررسی شده است.",
		"alreadyArchived":        "این {0} قبلا آرشیو شده است.",
		"statusNotChange":        "این {0} قبلا همین وضعیت را داشته است.",
		"alreadyCanceled":        "این {0} قبلا لغو شده است.",
		"alreadyRejected":        "این {0} قبلا رد شده است.",
		"alreadyAccepted":        "این {0} قبلا قبول شده است.",
		"alreadyDraft":           "این {0} قبلا در حالت پیش نویس قرار گرفته است.",
	},
	"successMessage": map[string]interface{}{
		"userRegister":              "ثبت نام موفق بود! لطفاً پیامک های خود را بررسی کنید تا حساب خود را تأیید کرده و فرآیند ثبت نام را تکمیل نمایید.",
		"phoneVerification":         "شماره شما با موفقیت تایید شد.",
		"login":                     "شما با موفقیت وارد شدید.",
		"changeLogo":                "لوگوی شرکت ب موفقیت عوض شد.",
		"addAddress":                "آدرس با موفقیت اضافه شد.",
		"editAddress":               "آدرس با موفقیت ویرایش شد.",
		"deleteAddress":             "آدرس با موفقیت حذف شد.",
		"changePassword":            "رمز عبور با موفقیت تغییر کرد.",
		"forgotPassword":            "لطفا پیامک های خود را بررسی کنید تا تلفن خود را تایید نمایید .",
		"resetPassword":             "گذرواژه با موفقیت تغییر کرد.",
		"createAddress":             "آدرس مورد نظر با موفقیت اضافه شد.",
		"refreshToken":              "نشست شما با موفقیت تمدید شد.",
		"readNotification":          "اعلان با موفقیت خوانده شد.",
		"updateNotificationSetting": "تنظیمات اعلان های شما به روزرسانی شد.",
		"completeRegister":          "اطلاعات تکمیلی ثبت نام با موفقیت انجام شد.",
		"emailVerification":         "ایمیل شما با موفقیت تایید شد.",
		"updateProfile":             "پروفایل شما با موفقیت به روزرسانی شد.",
		"blockChatRoom":             "اتاق گفتگو با موفقیت مسدود شد.",
		"unblockChatRoom":           "اتاق گفتگو با موفقیت رفع مسدود شد.",
		"createRole":                "نقش جدید با موفقیت ساخته شد.",
		"deleteRole":                "نقش مورد نظر با موفقیت حذف شد..",
		"updateRole":                "نقش مورد نظر با موفقیت به روزرسانی شد.",
		"updateUserRoles":           "نقش های فرد مورد نظر به روزرسانی شد.",
		"banUser":                   "کاربر با موفقیت محدود شد.",
		"unBanUser":                 "کاربر با موفقیت رفع محدود شد.",
		"createDraftNews":           "پیش نویس خبر با موفقیت ساخته شد.",
		"editNews":                  "خبر با موفقیت به روز رسانی شد.",
		"publishNews":               "خبر با موفقیت منتشر شد.",
		"unpublishNews":             "خبر با موفقیت به حالت پیش نویس تغییر کرد.",
		"deleteNews":                "اخبار مورد نظر شما با موفقیت حذف شدند.",
		"addMedia":                  "محتوای مورد نظر با موفقیت آپلود شد.",
		"deleteMedia":               "محتوای مورد نظر با موفقیت حذف شد.",
		"createPost":                "پست با موفقیت ساخته شد.",
		"deletePost":                "پست با موفقیت حذف شد.",
		"editPost":                  "پست با موفقیت به روز رسانی شد.",
		"publishPost":               "پست با موفقیت منتشر شد.",
		"unpublishPost":             "پست با موفقیت به حالت پیش نویس تغییر کرد.",
		"likePost":                  "پست با موفقیت لایک شد.",
		"unlikePost":                "لایک پست با موفقیت حذف شد.",
	},
	"emailSubject": map[string]interface{}{
		"emailConfirmation": "تأیید آدرس ایمیل شما",
	},
}
